// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go
//
// Generated by this command:
//
//	mockgen -source=admin.go -destination=mocks/admin_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domains "github.com/harrison542002/go-route/internal/core/domains"
	ports "github.com/harrison542002/go-route/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockAdmin is a mock of Admin interface.
type MockAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMockRecorder
	isgomock struct{}
}

// MockAdminMockRecorder is the mock recorder for MockAdmin.
type MockAdminMockRecorder struct {
	mock *MockAdmin
}

// NewMockAdmin creates a new mock instance.
func NewMockAdmin(ctrl *gomock.Controller) *MockAdmin {
	mock := &MockAdmin{ctrl: ctrl}
	mock.recorder = &MockAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdmin) EXPECT() *MockAdminMockRecorder {
	return m.recorder
}

// CreateAPIKey mocks base method.
func (m *MockAdmin) CreateAPIKey(ctx context.Context, w ports.Write, tenantRef string, in ports.NewAPIKey) (ports.IssuedAPIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIKey", ctx, w, tenantRef, in)
	ret0, _ := ret[0].(ports.IssuedAPIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockAdminMockRecorder) CreateAPIKey(ctx, w, tenantRef, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockAdmin)(nil).CreateAPIKey), ctx, w, tenantRef, in)
}

// CreateTenant mocks base method.
func (m *MockAdmin) CreateTenant(ctx context.Context, w ports.Write, in ports.NewTenant) (ports.TenantCreated, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, w, in)
	ret0, _ := ret[0].(ports.TenantCreated)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockAdminMockRecorder) CreateTenant(ctx, w, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockAdmin)(nil).CreateTenant), ctx, w, in)
}

// DeleteQuota mocks base method.
func (m *MockAdmin) DeleteQuota(ctx context.Context, w ports.Write, tenantRef string, kind domains.WindowKind) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteQuota", ctx, w, tenantRef, kind)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteQuota indicates an expected call of DeleteQuota.
func (mr *MockAdminMockRecorder) DeleteQuota(ctx, w, tenantRef, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteQuota", reflect.TypeOf((*MockAdmin)(nil).DeleteQuota), ctx, w, tenantRef, kind)
}

// DisableTenant mocks base method.
func (m *MockAdmin) DisableTenant(ctx context.Context, w ports.Write, tenantRef string) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableTenant", ctx, w, tenantRef)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableTenant indicates an expected call of DisableTenant.
func (mr *MockAdminMockRecorder) DisableTenant(ctx, w, tenantRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableTenant", reflect.TypeOf((*MockAdmin)(nil).DisableTenant), ctx, w, tenantRef)
}

// EnableTenant mocks base method.
func (m *MockAdmin) EnableTenant(ctx context.Context, w ports.Write, tenantRef string) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableTenant", ctx, w, tenantRef)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableTenant indicates an expected call of EnableTenant.
func (mr *MockAdminMockRecorder) EnableTenant(ctx, w, tenantRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableTenant", reflect.TypeOf((*MockAdmin)(nil).EnableTenant), ctx, w, tenantRef)
}

// GetAPIKey mocks base method.
func (m *MockAdmin) GetAPIKey(ctx context.Context, id uuid.UUID) (domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIKey", ctx, id)
	ret0, _ := ret[0].(domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockAdminMockRecorder) GetAPIKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockAdmin)(nil).GetAPIKey), ctx, id)
}

// GetQuota mocks base method.
func (m *MockAdmin) GetQuota(ctx context.Context, tenantRef string, kind domains.WindowKind) (domains.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuota", ctx, tenantRef, kind)
	ret0, _ := ret[0].(domains.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuota indicates an expected call of GetQuota.
func (mr *MockAdminMockRecorder) GetQuota(ctx, tenantRef, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuota", reflect.TypeOf((*MockAdmin)(nil).GetQuota), ctx, tenantRef, kind)
}

// GetTenant mocks base method.
func (m *MockAdmin) GetTenant(ctx context.Context, tenantRef string) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", ctx, tenantRef)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockAdminMockRecorder) GetTenant(ctx, tenantRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockAdmin)(nil).GetTenant), ctx, tenantRef)
}

// ListAPIKeys mocks base method.
func (m *MockAdmin) ListAPIKeys(ctx context.Context, tenantRef string) ([]domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPIKeys", ctx, tenantRef)
	ret0, _ := ret[0].([]domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPIKeys indicates an expected call of ListAPIKeys.
func (mr *MockAdminMockRecorder) ListAPIKeys(ctx, tenantRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIKeys", reflect.TypeOf((*MockAdmin)(nil).ListAPIKeys), ctx, tenantRef)
}

// ListQuotas mocks base method.
func (m *MockAdmin) ListQuotas(ctx context.Context, tenantRef string) ([]domains.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListQuotas", ctx, tenantRef)
	ret0, _ := ret[0].([]domains.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListQuotas indicates an expected call of ListQuotas.
func (mr *MockAdminMockRecorder) ListQuotas(ctx, tenantRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListQuotas", reflect.TypeOf((*MockAdmin)(nil).ListQuotas), ctx, tenantRef)
}

// ListTenants mocks base method.
func (m *MockAdmin) ListTenants(ctx context.Context, f ports.TenantFilter) ([]domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenants", ctx, f)
	ret0, _ := ret[0].([]domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTenants indicates an expected call of ListTenants.
func (mr *MockAdminMockRecorder) ListTenants(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenants", reflect.TypeOf((*MockAdmin)(nil).ListTenants), ctx, f)
}

// PutQuota mocks base method.
func (m *MockAdmin) PutQuota(ctx context.Context, w ports.Write, tenantRef string, q domains.Quota) (domains.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutQuota", ctx, w, tenantRef, q)
	ret0, _ := ret[0].(domains.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutQuota indicates an expected call of PutQuota.
func (mr *MockAdminMockRecorder) PutQuota(ctx, w, tenantRef, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutQuota", reflect.TypeOf((*MockAdmin)(nil).PutQuota), ctx, w, tenantRef, q)
}

// ReplaceQuotas mocks base method.
func (m *MockAdmin) ReplaceQuotas(ctx context.Context, w ports.Write, tenantRef string, set []domains.Quota) ([]domains.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceQuotas", ctx, w, tenantRef, set)
	ret0, _ := ret[0].([]domains.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceQuotas indicates an expected call of ReplaceQuotas.
func (mr *MockAdminMockRecorder) ReplaceQuotas(ctx, w, tenantRef, set any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceQuotas", reflect.TypeOf((*MockAdmin)(nil).ReplaceQuotas), ctx, w, tenantRef, set)
}

// RevokeAPIKey mocks base method.
func (m *MockAdmin) RevokeAPIKey(ctx context.Context, w ports.Write, id uuid.UUID) (domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAPIKey", ctx, w, id)
	ret0, _ := ret[0].(domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAPIKey indicates an expected call of RevokeAPIKey.
func (mr *MockAdminMockRecorder) RevokeAPIKey(ctx, w, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAPIKey", reflect.TypeOf((*MockAdmin)(nil).RevokeAPIKey), ctx, w, id)
}

// UpdateAPIKey mocks base method.
func (m *MockAdmin) UpdateAPIKey(ctx context.Context, w ports.Write, id uuid.UUID, p ports.APIKeyPatch) (domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAPIKey", ctx, w, id, p)
	ret0, _ := ret[0].(domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAPIKey indicates an expected call of UpdateAPIKey.
func (mr *MockAdminMockRecorder) UpdateAPIKey(ctx, w, id, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAPIKey", reflect.TypeOf((*MockAdmin)(nil).UpdateAPIKey), ctx, w, id, p)
}

// UpdateTenant mocks base method.
func (m *MockAdmin) UpdateTenant(ctx context.Context, w ports.Write, tenantRef string, p ports.TenantPatch) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", ctx, w, tenantRef, p)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockAdminMockRecorder) UpdateTenant(ctx, w, tenantRef, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockAdmin)(nil).UpdateTenant), ctx, w, tenantRef, p)
}

// MockTenantReader is a mock of TenantReader interface.
type MockTenantReader struct {
	ctrl     *gomock.Controller
	recorder *MockTenantReaderMockRecorder
	isgomock struct{}
}

// MockTenantReaderMockRecorder is the mock recorder for MockTenantReader.
type MockTenantReaderMockRecorder struct {
	mock *MockTenantReader
}

// NewMockTenantReader creates a new mock instance.
func NewMockTenantReader(ctrl *gomock.Controller) *MockTenantReader {
	mock := &MockTenantReader{ctrl: ctrl}
	mock.recorder = &MockTenantReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantReader) EXPECT() *MockTenantReaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTenantReader) Get(ctx context.Context, id uuid.UUID) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTenantReaderMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTenantReader)(nil).Get), ctx, id)
}

// GetByExternalID mocks base method.
func (m *MockTenantReader) GetByExternalID(ctx context.Context, externalID string) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalID", ctx, externalID)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalID indicates an expected call of GetByExternalID.
func (mr *MockTenantReaderMockRecorder) GetByExternalID(ctx, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalID", reflect.TypeOf((*MockTenantReader)(nil).GetByExternalID), ctx, externalID)
}

// List mocks base method.
func (m *MockTenantReader) List(ctx context.Context, f ports.TenantFilter) ([]domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, f)
	ret0, _ := ret[0].([]domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTenantReaderMockRecorder) List(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantReader)(nil).List), ctx, f)
}

// MockTenantRepository is a mock of TenantRepository interface.
type MockTenantRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTenantRepositoryMockRecorder
	isgomock struct{}
}

// MockTenantRepositoryMockRecorder is the mock recorder for MockTenantRepository.
type MockTenantRepositoryMockRecorder struct {
	mock *MockTenantRepository
}

// NewMockTenantRepository creates a new mock instance.
func NewMockTenantRepository(ctrl *gomock.Controller) *MockTenantRepository {
	mock := &MockTenantRepository{ctrl: ctrl}
	mock.recorder = &MockTenantRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantRepository) EXPECT() *MockTenantRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantRepository) Create(ctx context.Context, t domains.TenantAccount) (domains.TenantAccount, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockTenantRepositoryMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantRepository)(nil).Create), ctx, t)
}

// Disable mocks base method.
func (m *MockTenantRepository) Disable(ctx context.Context, id uuid.UUID) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx, id)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Disable indicates an expected call of Disable.
func (mr *MockTenantRepositoryMockRecorder) Disable(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockTenantRepository)(nil).Disable), ctx, id)
}

// Enable mocks base method.
func (m *MockTenantRepository) Enable(ctx context.Context, id uuid.UUID) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enable", ctx, id)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enable indicates an expected call of Enable.
func (mr *MockTenantRepositoryMockRecorder) Enable(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enable", reflect.TypeOf((*MockTenantRepository)(nil).Enable), ctx, id)
}

// Get mocks base method.
func (m *MockTenantRepository) Get(ctx context.Context, id uuid.UUID) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTenantRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTenantRepository)(nil).Get), ctx, id)
}

// GetByExternalID mocks base method.
func (m *MockTenantRepository) GetByExternalID(ctx context.Context, externalID string) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalID", ctx, externalID)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalID indicates an expected call of GetByExternalID.
func (mr *MockTenantRepositoryMockRecorder) GetByExternalID(ctx, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalID", reflect.TypeOf((*MockTenantRepository)(nil).GetByExternalID), ctx, externalID)
}

// List mocks base method.
func (m *MockTenantRepository) List(ctx context.Context, f ports.TenantFilter) ([]domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, f)
	ret0, _ := ret[0].([]domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTenantRepositoryMockRecorder) List(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantRepository)(nil).List), ctx, f)
}

// Lock mocks base method.
func (m *MockTenantRepository) Lock(ctx context.Context, id uuid.UUID) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, id)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lock indicates an expected call of Lock.
func (mr *MockTenantRepositoryMockRecorder) Lock(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockTenantRepository)(nil).Lock), ctx, id)
}

// Update mocks base method.
func (m *MockTenantRepository) Update(ctx context.Context, id uuid.UUID, p ports.TenantPatch) (domains.TenantAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, p)
	ret0, _ := ret[0].(domains.TenantAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTenantRepositoryMockRecorder) Update(ctx, id, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantRepository)(nil).Update), ctx, id, p)
}

// MockAPIKeyReader is a mock of APIKeyReader interface.
type MockAPIKeyReader struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyReaderMockRecorder
	isgomock struct{}
}

// MockAPIKeyReaderMockRecorder is the mock recorder for MockAPIKeyReader.
type MockAPIKeyReaderMockRecorder struct {
	mock *MockAPIKeyReader
}

// NewMockAPIKeyReader creates a new mock instance.
func NewMockAPIKeyReader(ctrl *gomock.Controller) *MockAPIKeyReader {
	mock := &MockAPIKeyReader{ctrl: ctrl}
	mock.recorder = &MockAPIKeyReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyReader) EXPECT() *MockAPIKeyReaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockAPIKeyReader) Get(ctx context.Context, id uuid.UUID) (domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAPIKeyReaderMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAPIKeyReader)(nil).Get), ctx, id)
}

// ListByTenant mocks base method.
func (m *MockAPIKeyReader) ListByTenant(ctx context.Context, tenantID uuid.UUID) ([]domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenant indicates an expected call of ListByTenant.
func (mr *MockAPIKeyReaderMockRecorder) ListByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenant", reflect.TypeOf((*MockAPIKeyReader)(nil).ListByTenant), ctx, tenantID)
}

// MockAPIKeyRepository is a mock of APIKeyRepository interface.
type MockAPIKeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAPIKeyRepositoryMockRecorder
	isgomock struct{}
}

// MockAPIKeyRepositoryMockRecorder is the mock recorder for MockAPIKeyRepository.
type MockAPIKeyRepositoryMockRecorder struct {
	mock *MockAPIKeyRepository
}

// NewMockAPIKeyRepository creates a new mock instance.
func NewMockAPIKeyRepository(ctrl *gomock.Controller) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{ctrl: ctrl}
	mock.recorder = &MockAPIKeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAPIKeyRepository) Create(ctx context.Context, k domains.APIKey, hash []byte) (domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, k, hash)
	ret0, _ := ret[0].(domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAPIKeyRepositoryMockRecorder) Create(ctx, k, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAPIKeyRepository)(nil).Create), ctx, k, hash)
}

// Get mocks base method.
func (m *MockAPIKeyRepository) Get(ctx context.Context, id uuid.UUID) (domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAPIKeyRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAPIKeyRepository)(nil).Get), ctx, id)
}

// ListByTenant mocks base method.
func (m *MockAPIKeyRepository) ListByTenant(ctx context.Context, tenantID uuid.UUID) ([]domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTenant", ctx, tenantID)
	ret0, _ := ret[0].([]domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTenant indicates an expected call of ListByTenant.
func (mr *MockAPIKeyRepositoryMockRecorder) ListByTenant(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTenant", reflect.TypeOf((*MockAPIKeyRepository)(nil).ListByTenant), ctx, tenantID)
}

// Revoke mocks base method.
func (m *MockAPIKeyRepository) Revoke(ctx context.Context, id uuid.UUID) (domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAPIKeyRepositoryMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAPIKeyRepository)(nil).Revoke), ctx, id)
}

// UpdateAllowlist mocks base method.
func (m *MockAPIKeyRepository) UpdateAllowlist(ctx context.Context, id uuid.UUID, allowlist []string) (domains.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllowlist", ctx, id, allowlist)
	ret0, _ := ret[0].(domains.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAllowlist indicates an expected call of UpdateAllowlist.
func (mr *MockAPIKeyRepositoryMockRecorder) UpdateAllowlist(ctx, id, allowlist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllowlist", reflect.TypeOf((*MockAPIKeyRepository)(nil).UpdateAllowlist), ctx, id, allowlist)
}

// MockQuotaReader is a mock of QuotaReader interface.
type MockQuotaReader struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaReaderMockRecorder
	isgomock struct{}
}

// MockQuotaReaderMockRecorder is the mock recorder for MockQuotaReader.
type MockQuotaReaderMockRecorder struct {
	mock *MockQuotaReader
}

// NewMockQuotaReader creates a new mock instance.
func NewMockQuotaReader(ctrl *gomock.Controller) *MockQuotaReader {
	mock := &MockQuotaReader{ctrl: ctrl}
	mock.recorder = &MockQuotaReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaReader) EXPECT() *MockQuotaReaderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockQuotaReader) Get(ctx context.Context, tenantID uuid.UUID, kind domains.WindowKind) (domains.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tenantID, kind)
	ret0, _ := ret[0].(domains.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockQuotaReaderMockRecorder) Get(ctx, tenantID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockQuotaReader)(nil).Get), ctx, tenantID, kind)
}

// List mocks base method.
func (m *MockQuotaReader) List(ctx context.Context, tenantID uuid.UUID) ([]domains.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID)
	ret0, _ := ret[0].([]domains.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockQuotaReaderMockRecorder) List(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockQuotaReader)(nil).List), ctx, tenantID)
}

// MockQuotaRepository is a mock of QuotaRepository interface.
type MockQuotaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaRepositoryMockRecorder
	isgomock struct{}
}

// MockQuotaRepositoryMockRecorder is the mock recorder for MockQuotaRepository.
type MockQuotaRepositoryMockRecorder struct {
	mock *MockQuotaRepository
}

// NewMockQuotaRepository creates a new mock instance.
func NewMockQuotaRepository(ctrl *gomock.Controller) *MockQuotaRepository {
	mock := &MockQuotaRepository{ctrl: ctrl}
	mock.recorder = &MockQuotaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaRepository) EXPECT() *MockQuotaRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockQuotaRepository) Delete(ctx context.Context, tenantID uuid.UUID, kind domains.WindowKind) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tenantID, kind)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockQuotaRepositoryMockRecorder) Delete(ctx, tenantID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQuotaRepository)(nil).Delete), ctx, tenantID, kind)
}

// DeleteAll mocks base method.
func (m *MockQuotaRepository) DeleteAll(ctx context.Context, tenantID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MockQuotaRepositoryMockRecorder) DeleteAll(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MockQuotaRepository)(nil).DeleteAll), ctx, tenantID)
}

// Get mocks base method.
func (m *MockQuotaRepository) Get(ctx context.Context, tenantID uuid.UUID, kind domains.WindowKind) (domains.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tenantID, kind)
	ret0, _ := ret[0].(domains.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockQuotaRepositoryMockRecorder) Get(ctx, tenantID, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockQuotaRepository)(nil).Get), ctx, tenantID, kind)
}

// List mocks base method.
func (m *MockQuotaRepository) List(ctx context.Context, tenantID uuid.UUID) ([]domains.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, tenantID)
	ret0, _ := ret[0].([]domains.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockQuotaRepositoryMockRecorder) List(ctx, tenantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockQuotaRepository)(nil).List), ctx, tenantID)
}

// Upsert mocks base method.
func (m *MockQuotaRepository) Upsert(ctx context.Context, tenantID uuid.UUID, q domains.Quota) (domains.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, tenantID, q)
	ret0, _ := ret[0].(domains.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockQuotaRepositoryMockRecorder) Upsert(ctx, tenantID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockQuotaRepository)(nil).Upsert), ctx, tenantID, q)
}

// MockAuditRepository is a mock of AuditRepository interface.
type MockAuditRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuditRepositoryMockRecorder
	isgomock struct{}
}

// MockAuditRepositoryMockRecorder is the mock recorder for MockAuditRepository.
type MockAuditRepositoryMockRecorder struct {
	mock *MockAuditRepository
}

// NewMockAuditRepository creates a new mock instance.
func NewMockAuditRepository(ctrl *gomock.Controller) *MockAuditRepository {
	mock := &MockAuditRepository{ctrl: ctrl}
	mock.recorder = &MockAuditRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditRepository) EXPECT() *MockAuditRepositoryMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *MockAuditRepository) Write(ctx context.Context, e ports.AuditEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockAuditRepositoryMockRecorder) Write(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockAuditRepository)(nil).Write), ctx, e)
}

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// APIKeys mocks base method.
func (m *MockAdminRepository) APIKeys() ports.APIKeyReader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIKeys")
	ret0, _ := ret[0].(ports.APIKeyReader)
	return ret0
}

// APIKeys indicates an expected call of APIKeys.
func (mr *MockAdminRepositoryMockRecorder) APIKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIKeys", reflect.TypeOf((*MockAdminRepository)(nil).APIKeys))
}

// InTx mocks base method.
func (m *MockAdminRepository) InTx(ctx context.Context, fn func(context.Context, ports.AdminTx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InTx indicates an expected call of InTx.
func (mr *MockAdminRepositoryMockRecorder) InTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InTx", reflect.TypeOf((*MockAdminRepository)(nil).InTx), ctx, fn)
}

// Quotas mocks base method.
func (m *MockAdminRepository) Quotas() ports.QuotaReader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quotas")
	ret0, _ := ret[0].(ports.QuotaReader)
	return ret0
}

// Quotas indicates an expected call of Quotas.
func (mr *MockAdminRepositoryMockRecorder) Quotas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quotas", reflect.TypeOf((*MockAdminRepository)(nil).Quotas))
}

// Tenants mocks base method.
func (m *MockAdminRepository) Tenants() ports.TenantReader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tenants")
	ret0, _ := ret[0].(ports.TenantReader)
	return ret0
}

// Tenants indicates an expected call of Tenants.
func (mr *MockAdminRepositoryMockRecorder) Tenants() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tenants", reflect.TypeOf((*MockAdminRepository)(nil).Tenants))
}

// MockAdminTx is a mock of AdminTx interface.
type MockAdminTx struct {
	ctrl     *gomock.Controller
	recorder *MockAdminTxMockRecorder
	isgomock struct{}
}

// MockAdminTxMockRecorder is the mock recorder for MockAdminTx.
type MockAdminTxMockRecorder struct {
	mock *MockAdminTx
}

// NewMockAdminTx creates a new mock instance.
func NewMockAdminTx(ctrl *gomock.Controller) *MockAdminTx {
	mock := &MockAdminTx{ctrl: ctrl}
	mock.recorder = &MockAdminTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminTx) EXPECT() *MockAdminTxMockRecorder {
	return m.recorder
}

// APIKeys mocks base method.
func (m *MockAdminTx) APIKeys() ports.APIKeyRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIKeys")
	ret0, _ := ret[0].(ports.APIKeyRepository)
	return ret0
}

// APIKeys indicates an expected call of APIKeys.
func (mr *MockAdminTxMockRecorder) APIKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIKeys", reflect.TypeOf((*MockAdminTx)(nil).APIKeys))
}

// Audit mocks base method.
func (m *MockAdminTx) Audit() ports.AuditRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Audit")
	ret0, _ := ret[0].(ports.AuditRepository)
	return ret0
}

// Audit indicates an expected call of Audit.
func (mr *MockAdminTxMockRecorder) Audit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Audit", reflect.TypeOf((*MockAdminTx)(nil).Audit))
}

// Quotas mocks base method.
func (m *MockAdminTx) Quotas() ports.QuotaRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quotas")
	ret0, _ := ret[0].(ports.QuotaRepository)
	return ret0
}

// Quotas indicates an expected call of Quotas.
func (mr *MockAdminTxMockRecorder) Quotas() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quotas", reflect.TypeOf((*MockAdminTx)(nil).Quotas))
}

// Tenants mocks base method.
func (m *MockAdminTx) Tenants() ports.TenantRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tenants")
	ret0, _ := ret[0].(ports.TenantRepository)
	return ret0
}

// Tenants indicates an expected call of Tenants.
func (mr *MockAdminTxMockRecorder) Tenants() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tenants", reflect.TypeOf((*MockAdminTx)(nil).Tenants))
}
