// Code generated by MockGen. DO NOT EDIT.
// Source: admin_credentials.go
//
// Generated by this command:
//
//	mockgen -source=admin_credentials.go -destination=mocks/admin_credentials_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domains "github.com/harrison542002/go-route/internal/core/domains"
	ports "github.com/harrison542002/go-route/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminAuthenticator is a mock of AdminAuthenticator interface.
type MockAdminAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAdminAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAdminAuthenticatorMockRecorder is the mock recorder for MockAdminAuthenticator.
type MockAdminAuthenticatorMockRecorder struct {
	mock *MockAdminAuthenticator
}

// NewMockAdminAuthenticator creates a new mock instance.
func NewMockAdminAuthenticator(ctrl *gomock.Controller) *MockAdminAuthenticator {
	mock := &MockAdminAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAdminAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminAuthenticator) EXPECT() *MockAdminAuthenticatorMockRecorder {
	return m.recorder
}

// AdminCredentialByTokenHash mocks base method.
func (m *MockAdminAuthenticator) AdminCredentialByTokenHash(ctx context.Context, tokenHash []byte) (domains.AdminCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCredentialByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(domains.AdminCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminCredentialByTokenHash indicates an expected call of AdminCredentialByTokenHash.
func (mr *MockAdminAuthenticatorMockRecorder) AdminCredentialByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCredentialByTokenHash", reflect.TypeOf((*MockAdminAuthenticator)(nil).AdminCredentialByTokenHash), ctx, tokenHash)
}

// TouchAdminCredential mocks base method.
func (m *MockAdminAuthenticator) TouchAdminCredential(ctx context.Context, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchAdminCredential", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchAdminCredential indicates an expected call of TouchAdminCredential.
func (mr *MockAdminAuthenticatorMockRecorder) TouchAdminCredential(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchAdminCredential", reflect.TypeOf((*MockAdminAuthenticator)(nil).TouchAdminCredential), ctx, id, at)
}

// MockAdminCredentialRepository is a mock of AdminCredentialRepository interface.
type MockAdminCredentialRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminCredentialRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminCredentialRepositoryMockRecorder is the mock recorder for MockAdminCredentialRepository.
type MockAdminCredentialRepositoryMockRecorder struct {
	mock *MockAdminCredentialRepository
}

// NewMockAdminCredentialRepository creates a new mock instance.
func NewMockAdminCredentialRepository(ctrl *gomock.Controller) *MockAdminCredentialRepository {
	mock := &MockAdminCredentialRepository{ctrl: ctrl}
	mock.recorder = &MockAdminCredentialRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminCredentialRepository) EXPECT() *MockAdminCredentialRepositoryMockRecorder {
	return m.recorder
}

// AdminCredentialByRef mocks base method.
func (m *MockAdminCredentialRepository) AdminCredentialByRef(ctx context.Context, ref string) (domains.AdminCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCredentialByRef", ctx, ref)
	ret0, _ := ret[0].(domains.AdminCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminCredentialByRef indicates an expected call of AdminCredentialByRef.
func (mr *MockAdminCredentialRepositoryMockRecorder) AdminCredentialByRef(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCredentialByRef", reflect.TypeOf((*MockAdminCredentialRepository)(nil).AdminCredentialByRef), ctx, ref)
}

// AdminCredentialByTokenHash mocks base method.
func (m *MockAdminCredentialRepository) AdminCredentialByTokenHash(ctx context.Context, tokenHash []byte) (domains.AdminCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCredentialByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(domains.AdminCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminCredentialByTokenHash indicates an expected call of AdminCredentialByTokenHash.
func (mr *MockAdminCredentialRepositoryMockRecorder) AdminCredentialByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCredentialByTokenHash", reflect.TypeOf((*MockAdminCredentialRepository)(nil).AdminCredentialByTokenHash), ctx, tokenHash)
}

// CreateAdminCredential mocks base method.
func (m *MockAdminCredentialRepository) CreateAdminCredential(ctx context.Context, c domains.AdminCredential, tokenHash []byte, e ports.AuditEntry) (domains.AdminCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminCredential", ctx, c, tokenHash, e)
	ret0, _ := ret[0].(domains.AdminCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminCredential indicates an expected call of CreateAdminCredential.
func (mr *MockAdminCredentialRepositoryMockRecorder) CreateAdminCredential(ctx, c, tokenHash, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminCredential", reflect.TypeOf((*MockAdminCredentialRepository)(nil).CreateAdminCredential), ctx, c, tokenHash, e)
}

// ListAdminCredentials mocks base method.
func (m *MockAdminCredentialRepository) ListAdminCredentials(ctx context.Context) ([]domains.AdminCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminCredentials", ctx)
	ret0, _ := ret[0].([]domains.AdminCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminCredentials indicates an expected call of ListAdminCredentials.
func (mr *MockAdminCredentialRepositoryMockRecorder) ListAdminCredentials(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminCredentials", reflect.TypeOf((*MockAdminCredentialRepository)(nil).ListAdminCredentials), ctx)
}

// RevokeAdminCredential mocks base method.
func (m *MockAdminCredentialRepository) RevokeAdminCredential(ctx context.Context, id uuid.UUID, e ports.AuditEntry) (domains.AdminCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAdminCredential", ctx, id, e)
	ret0, _ := ret[0].(domains.AdminCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAdminCredential indicates an expected call of RevokeAdminCredential.
func (mr *MockAdminCredentialRepositoryMockRecorder) RevokeAdminCredential(ctx, id, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAdminCredential", reflect.TypeOf((*MockAdminCredentialRepository)(nil).RevokeAdminCredential), ctx, id, e)
}

// TouchAdminCredential mocks base method.
func (m *MockAdminCredentialRepository) TouchAdminCredential(ctx context.Context, id uuid.UUID, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchAdminCredential", ctx, id, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchAdminCredential indicates an expected call of TouchAdminCredential.
func (mr *MockAdminCredentialRepositoryMockRecorder) TouchAdminCredential(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchAdminCredential", reflect.TypeOf((*MockAdminCredentialRepository)(nil).TouchAdminCredential), ctx, id, at)
}
