// Code generated by MockGen. DO NOT EDIT.
// Source: admin_users.go
//
// Generated by this command:
//
//	mockgen -source=admin_users.go -destination=mocks/admin_users_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domains "github.com/harrison542002/go-route/internal/core/domains"
	ports "github.com/harrison542002/go-route/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminUserAuthenticator is a mock of AdminUserAuthenticator interface.
type MockAdminUserAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserAuthenticatorMockRecorder
	isgomock struct{}
}

// MockAdminUserAuthenticatorMockRecorder is the mock recorder for MockAdminUserAuthenticator.
type MockAdminUserAuthenticatorMockRecorder struct {
	mock *MockAdminUserAuthenticator
}

// NewMockAdminUserAuthenticator creates a new mock instance.
func NewMockAdminUserAuthenticator(ctrl *gomock.Controller) *MockAdminUserAuthenticator {
	mock := &MockAdminUserAuthenticator{ctrl: ctrl}
	mock.recorder = &MockAdminUserAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserAuthenticator) EXPECT() *MockAdminUserAuthenticatorMockRecorder {
	return m.recorder
}

// AdminUserByID mocks base method.
func (m *MockAdminUserAuthenticator) AdminUserByID(ctx context.Context, id uuid.UUID) (domains.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUserByID", ctx, id)
	ret0, _ := ret[0].(domains.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminUserByID indicates an expected call of AdminUserByID.
func (mr *MockAdminUserAuthenticatorMockRecorder) AdminUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserByID", reflect.TypeOf((*MockAdminUserAuthenticator)(nil).AdminUserByID), ctx, id)
}

// MockAdminUserRepository is a mock of AdminUserRepository interface.
type MockAdminUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminUserRepositoryMockRecorder is the mock recorder for MockAdminUserRepository.
type MockAdminUserRepositoryMockRecorder struct {
	mock *MockAdminUserRepository
}

// NewMockAdminUserRepository creates a new mock instance.
func NewMockAdminUserRepository(ctrl *gomock.Controller) *MockAdminUserRepository {
	mock := &MockAdminUserRepository{ctrl: ctrl}
	mock.recorder = &MockAdminUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserRepository) EXPECT() *MockAdminUserRepositoryMockRecorder {
	return m.recorder
}

// AdminSessionByTokenHash mocks base method.
func (m *MockAdminUserRepository) AdminSessionByTokenHash(ctx context.Context, tokenHash []byte) (ports.AdminSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminSessionByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(ports.AdminSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminSessionByTokenHash indicates an expected call of AdminSessionByTokenHash.
func (mr *MockAdminUserRepositoryMockRecorder) AdminSessionByTokenHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminSessionByTokenHash", reflect.TypeOf((*MockAdminUserRepository)(nil).AdminSessionByTokenHash), ctx, tokenHash)
}

// AdminUserByEmail mocks base method.
func (m *MockAdminUserRepository) AdminUserByEmail(ctx context.Context, email string) (domains.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUserByEmail", ctx, email)
	ret0, _ := ret[0].(domains.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminUserByEmail indicates an expected call of AdminUserByEmail.
func (mr *MockAdminUserRepositoryMockRecorder) AdminUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserByEmail", reflect.TypeOf((*MockAdminUserRepository)(nil).AdminUserByEmail), ctx, email)
}

// AdminUserByID mocks base method.
func (m *MockAdminUserRepository) AdminUserByID(ctx context.Context, id uuid.UUID) (domains.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUserByID", ctx, id)
	ret0, _ := ret[0].(domains.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminUserByID indicates an expected call of AdminUserByID.
func (mr *MockAdminUserRepositoryMockRecorder) AdminUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserByID", reflect.TypeOf((*MockAdminUserRepository)(nil).AdminUserByID), ctx, id)
}

// AdminUserForLogin mocks base method.
func (m *MockAdminUserRepository) AdminUserForLogin(ctx context.Context, email string) (domains.AdminUser, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUserForLogin", ctx, email)
	ret0, _ := ret[0].(domains.AdminUser)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AdminUserForLogin indicates an expected call of AdminUserForLogin.
func (mr *MockAdminUserRepositoryMockRecorder) AdminUserForLogin(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserForLogin", reflect.TypeOf((*MockAdminUserRepository)(nil).AdminUserForLogin), ctx, email)
}

// CreateAdminUser mocks base method.
func (m *MockAdminUserRepository) CreateAdminUser(ctx context.Context, u domains.AdminUser, passwordHash string, e ports.AuditEntry) (domains.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAdminUser", ctx, u, passwordHash, e)
	ret0, _ := ret[0].(domains.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAdminUser indicates an expected call of CreateAdminUser.
func (mr *MockAdminUserRepositoryMockRecorder) CreateAdminUser(ctx, u, passwordHash, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAdminUser", reflect.TypeOf((*MockAdminUserRepository)(nil).CreateAdminUser), ctx, u, passwordHash, e)
}

// DisableAdminUser mocks base method.
func (m *MockAdminUserRepository) DisableAdminUser(ctx context.Context, id uuid.UUID, at time.Time, e ports.AuditEntry) (domains.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisableAdminUser", ctx, id, at, e)
	ret0, _ := ret[0].(domains.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DisableAdminUser indicates an expected call of DisableAdminUser.
func (mr *MockAdminUserRepositoryMockRecorder) DisableAdminUser(ctx, id, at, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisableAdminUser", reflect.TypeOf((*MockAdminUserRepository)(nil).DisableAdminUser), ctx, id, at, e)
}

// EndAdminSession mocks base method.
func (m *MockAdminUserRepository) EndAdminSession(ctx context.Context, id uuid.UUID, at time.Time, e ports.AuditEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndAdminSession", ctx, id, at, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndAdminSession indicates an expected call of EndAdminSession.
func (mr *MockAdminUserRepositoryMockRecorder) EndAdminSession(ctx, id, at, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndAdminSession", reflect.TypeOf((*MockAdminUserRepository)(nil).EndAdminSession), ctx, id, at, e)
}

// ListAdminUsers mocks base method.
func (m *MockAdminUserRepository) ListAdminUsers(ctx context.Context) ([]domains.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdminUsers", ctx)
	ret0, _ := ret[0].([]domains.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdminUsers indicates an expected call of ListAdminUsers.
func (mr *MockAdminUserRepositoryMockRecorder) ListAdminUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdminUsers", reflect.TypeOf((*MockAdminUserRepository)(nil).ListAdminUsers), ctx)
}

// RevokeAdminSessions mocks base method.
func (m *MockAdminUserRepository) RevokeAdminSessions(ctx context.Context, userID uuid.UUID, at time.Time, e ports.AuditEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAdminSessions", ctx, userID, at, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAdminSessions indicates an expected call of RevokeAdminSessions.
func (mr *MockAdminUserRepositoryMockRecorder) RevokeAdminSessions(ctx, userID, at, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAdminSessions", reflect.TypeOf((*MockAdminUserRepository)(nil).RevokeAdminSessions), ctx, userID, at, e)
}

// RotateAdminSession mocks base method.
func (m *MockAdminUserRepository) RotateAdminSession(ctx context.Context, presented uuid.UUID, s ports.NewAdminSession) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateAdminSession", ctx, presented, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateAdminSession indicates an expected call of RotateAdminSession.
func (mr *MockAdminUserRepositoryMockRecorder) RotateAdminSession(ctx, presented, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateAdminSession", reflect.TypeOf((*MockAdminUserRepository)(nil).RotateAdminSession), ctx, presented, s)
}

// SetAdminUserPassword mocks base method.
func (m *MockAdminUserRepository) SetAdminUserPassword(ctx context.Context, id uuid.UUID, passwordHash string, at time.Time, e ports.AuditEntry) (domains.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAdminUserPassword", ctx, id, passwordHash, at, e)
	ret0, _ := ret[0].(domains.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetAdminUserPassword indicates an expected call of SetAdminUserPassword.
func (mr *MockAdminUserRepositoryMockRecorder) SetAdminUserPassword(ctx, id, passwordHash, at, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAdminUserPassword", reflect.TypeOf((*MockAdminUserRepository)(nil).SetAdminUserPassword), ctx, id, passwordHash, at, e)
}

// StartAdminSession mocks base method.
func (m *MockAdminUserRepository) StartAdminSession(ctx context.Context, s ports.NewAdminSession, e ports.AuditEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartAdminSession", ctx, s, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartAdminSession indicates an expected call of StartAdminSession.
func (mr *MockAdminUserRepositoryMockRecorder) StartAdminSession(ctx, s, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAdminSession", reflect.TypeOf((*MockAdminUserRepository)(nil).StartAdminSession), ctx, s, e)
}

// WriteAudit mocks base method.
func (m *MockAdminUserRepository) WriteAudit(ctx context.Context, e ports.AuditEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteAudit", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteAudit indicates an expected call of WriteAudit.
func (mr *MockAdminUserRepositoryMockRecorder) WriteAudit(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteAudit", reflect.TypeOf((*MockAdminUserRepository)(nil).WriteAudit), ctx, e)
}

// MockAdminAuth is a mock of AdminAuth interface.
type MockAdminAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAdminAuthMockRecorder
	isgomock struct{}
}

// MockAdminAuthMockRecorder is the mock recorder for MockAdminAuth.
type MockAdminAuthMockRecorder struct {
	mock *MockAdminAuth
}

// NewMockAdminAuth creates a new mock instance.
func NewMockAdminAuth(ctrl *gomock.Controller) *MockAdminAuth {
	mock := &MockAdminAuth{ctrl: ctrl}
	mock.recorder = &MockAdminAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminAuth) EXPECT() *MockAdminAuthMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAdminAuth) Login(ctx context.Context, c ports.Credentials) (ports.AdminSessionTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, c)
	ret0, _ := ret[0].(ports.AdminSessionTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAdminAuthMockRecorder) Login(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAdminAuth)(nil).Login), ctx, c)
}

// Logout mocks base method.
func (m *MockAdminAuth) Logout(ctx context.Context, actor, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, actor, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAdminAuthMockRecorder) Logout(ctx, actor, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAdminAuth)(nil).Logout), ctx, actor, refreshToken)
}

// Refresh mocks base method.
func (m *MockAdminAuth) Refresh(ctx context.Context, refreshToken string) (ports.AdminSessionTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(ports.AdminSessionTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAdminAuthMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAdminAuth)(nil).Refresh), ctx, refreshToken)
}
