// Code generated by MockGen. DO NOT EDIT.
// Source: quota.go
//
// Generated by this command:
//
//	mockgen -source=quota.go -destination=mocks/quota_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domains "github.com/harrison542002/go-route/internal/core/domains"
	ports "github.com/harrison542002/go-route/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockQuotaEnforcer is a mock of QuotaEnforcer interface.
type MockQuotaEnforcer struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaEnforcerMockRecorder
	isgomock struct{}
}

// MockQuotaEnforcerMockRecorder is the mock recorder for MockQuotaEnforcer.
type MockQuotaEnforcerMockRecorder struct {
	mock *MockQuotaEnforcer
}

// NewMockQuotaEnforcer creates a new mock instance.
func NewMockQuotaEnforcer(ctrl *gomock.Controller) *MockQuotaEnforcer {
	mock := &MockQuotaEnforcer{ctrl: ctrl}
	mock.recorder = &MockQuotaEnforcerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaEnforcer) EXPECT() *MockQuotaEnforcerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method.
func (m *MockQuotaEnforcer) Reconcile(ctx context.Context, res ports.Reservation, outcome domains.Outcome) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reconcile", ctx, res, outcome)
}

// Reconcile indicates an expected call of Reconcile.
func (mr *MockQuotaEnforcerMockRecorder) Reconcile(ctx, res, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockQuotaEnforcer)(nil).Reconcile), ctx, res, outcome)
}

// Reserve mocks base method.
func (m *MockQuotaEnforcer) Reserve(ctx context.Context, req ports.QuotaRequest) (ports.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, req)
	ret0, _ := ret[0].(ports.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reserve indicates an expected call of Reserve.
func (mr *MockQuotaEnforcerMockRecorder) Reserve(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockQuotaEnforcer)(nil).Reserve), ctx, req)
}

// MockUsageCounterRepository is a mock of UsageCounterRepository interface.
type MockUsageCounterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsageCounterRepositoryMockRecorder
	isgomock struct{}
}

// MockUsageCounterRepositoryMockRecorder is the mock recorder for MockUsageCounterRepository.
type MockUsageCounterRepositoryMockRecorder struct {
	mock *MockUsageCounterRepository
}

// NewMockUsageCounterRepository creates a new mock instance.
func NewMockUsageCounterRepository(ctrl *gomock.Controller) *MockUsageCounterRepository {
	mock := &MockUsageCounterRepository{ctrl: ctrl}
	mock.recorder = &MockUsageCounterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageCounterRepository) EXPECT() *MockUsageCounterRepositoryMockRecorder {
	return m.recorder
}

// AddDeltas mocks base method.
func (m *MockUsageCounterRepository) AddDeltas(ctx context.Context, deltas []domains.WindowUsage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeltas", ctx, deltas)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDeltas indicates an expected call of AddDeltas.
func (mr *MockUsageCounterRepositoryMockRecorder) AddDeltas(ctx, deltas any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeltas", reflect.TypeOf((*MockUsageCounterRepository)(nil).AddDeltas), ctx, deltas)
}

// Get mocks base method.
func (m *MockUsageCounterRepository) Get(ctx context.Context, tenantID uuid.UUID, w domains.Window) (domains.QuotaUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tenantID, w)
	ret0, _ := ret[0].(domains.QuotaUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUsageCounterRepositoryMockRecorder) Get(ctx, tenantID, w any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUsageCounterRepository)(nil).Get), ctx, tenantID, w)
}

// MockQuotaCounters is a mock of QuotaCounters interface.
type MockQuotaCounters struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaCountersMockRecorder
	isgomock struct{}
}

// MockQuotaCountersMockRecorder is the mock recorder for MockQuotaCounters.
type MockQuotaCountersMockRecorder struct {
	mock *MockQuotaCounters
}

// NewMockQuotaCounters creates a new mock instance.
func NewMockQuotaCounters(ctrl *gomock.Controller) *MockQuotaCounters {
	mock := &MockQuotaCounters{ctrl: ctrl}
	mock.recorder = &MockQuotaCountersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaCounters) EXPECT() *MockQuotaCountersMockRecorder {
	return m.recorder
}

// Adjust mocks base method.
func (m *MockQuotaCounters) Adjust(ctx context.Context, tenantID uuid.UUID, windows []domains.Window, delta domains.QuotaUsage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Adjust", ctx, tenantID, windows, delta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Adjust indicates an expected call of Adjust.
func (mr *MockQuotaCountersMockRecorder) Adjust(ctx, tenantID, windows, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Adjust", reflect.TypeOf((*MockQuotaCounters)(nil).Adjust), ctx, tenantID, windows, delta)
}

// Reserve mocks base method.
func (m *MockQuotaCounters) Reserve(ctx context.Context, tenantID uuid.UUID, limits []domains.WindowLimit, amount domains.QuotaUsage) (ports.CounterReservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, tenantID, limits, amount)
	ret0, _ := ret[0].(ports.CounterReservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reserve indicates an expected call of Reserve.
func (mr *MockQuotaCountersMockRecorder) Reserve(ctx, tenantID, limits, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockQuotaCounters)(nil).Reserve), ctx, tenantID, limits, amount)
}

// Seed mocks base method.
func (m *MockQuotaCounters) Seed(ctx context.Context, seeds []domains.WindowUsage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seed", ctx, seeds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Seed indicates an expected call of Seed.
func (mr *MockQuotaCountersMockRecorder) Seed(ctx, seeds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seed", reflect.TypeOf((*MockQuotaCounters)(nil).Seed), ctx, seeds)
}
