// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mocks/store_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domains "github.com/harrison542002/go-route/internal/core/domains"
	ports "github.com/harrison542002/go-route/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockDecisionRepository is a mock of DecisionRepository interface.
type MockDecisionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDecisionRepositoryMockRecorder
	isgomock struct{}
}

// MockDecisionRepositoryMockRecorder is the mock recorder for MockDecisionRepository.
type MockDecisionRepositoryMockRecorder struct {
	mock *MockDecisionRepository
}

// NewMockDecisionRepository creates a new mock instance.
func NewMockDecisionRepository(ctrl *gomock.Controller) *MockDecisionRepository {
	mock := &MockDecisionRepository{ctrl: ctrl}
	mock.recorder = &MockDecisionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecisionRepository) EXPECT() *MockDecisionRepositoryMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *MockDecisionRepository) Aggregate(ctx context.Context, spec ports.ReportSpec) (domains.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", ctx, spec)
	ret0, _ := ret[0].(domains.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockDecisionRepositoryMockRecorder) Aggregate(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockDecisionRepository)(nil).Aggregate), ctx, spec)
}

// Get mocks base method.
func (m *MockDecisionRepository) Get(ctx context.Context, id domains.DecisionID) (domains.RoutingDecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domains.RoutingDecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDecisionRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDecisionRepository)(nil).Get), ctx, id)
}

// MockObservabilityRepository is a mock of ObservabilityRepository interface.
type MockObservabilityRepository struct {
	ctrl     *gomock.Controller
	recorder *MockObservabilityRepositoryMockRecorder
	isgomock struct{}
}

// MockObservabilityRepositoryMockRecorder is the mock recorder for MockObservabilityRepository.
type MockObservabilityRepositoryMockRecorder struct {
	mock *MockObservabilityRepository
}

// NewMockObservabilityRepository creates a new mock instance.
func NewMockObservabilityRepository(ctrl *gomock.Controller) *MockObservabilityRepository {
	mock := &MockObservabilityRepository{ctrl: ctrl}
	mock.recorder = &MockObservabilityRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObservabilityRepository) EXPECT() *MockObservabilityRepositoryMockRecorder {
	return m.recorder
}

// Aggregate mocks base method.
func (m *MockObservabilityRepository) Aggregate(ctx context.Context, spec ports.ReportSpec) (domains.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Aggregate", ctx, spec)
	ret0, _ := ret[0].(domains.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Aggregate indicates an expected call of Aggregate.
func (mr *MockObservabilityRepositoryMockRecorder) Aggregate(ctx, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Aggregate", reflect.TypeOf((*MockObservabilityRepository)(nil).Aggregate), ctx, spec)
}

// Get mocks base method.
func (m *MockObservabilityRepository) Get(ctx context.Context, id domains.DecisionID) (domains.RoutingDecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(domains.RoutingDecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockObservabilityRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObservabilityRepository)(nil).Get), ctx, id)
}

// ListAudit mocks base method.
func (m *MockObservabilityRepository) ListAudit(ctx context.Context, q ports.AuditQuery) (ports.AuditPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAudit", ctx, q)
	ret0, _ := ret[0].(ports.AuditPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAudit indicates an expected call of ListAudit.
func (mr *MockObservabilityRepositoryMockRecorder) ListAudit(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAudit", reflect.TypeOf((*MockObservabilityRepository)(nil).ListAudit), ctx, q)
}

// ResolveTenant mocks base method.
func (m *MockObservabilityRepository) ResolveTenant(ctx context.Context, ref string) (domains.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTenant", ctx, ref)
	ret0, _ := ret[0].(domains.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTenant indicates an expected call of ResolveTenant.
func (mr *MockObservabilityRepositoryMockRecorder) ResolveTenant(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTenant", reflect.TypeOf((*MockObservabilityRepository)(nil).ResolveTenant), ctx, ref)
}
